######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 1 15:28:32 2018
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += interfaceTest.cpp
